### ISSUE TITLE
Provider version is old

### ISSUE THREAD

**Issue by pishguy** [KarimElghamry/chillify#35]
i interested to know why you are use older version of Provider?

**Comment by KarimElghamry** [comment]
Hi @MahdiPishguy , thank you for checking out Chillify!

This app was made over 8 months ago, when the `Provider` package was still a new thing in Flutter. Refactoring the app using a newer version of the `Provider` package is not worth it in my opinion as I am only using the basic feature of the Provider. The main purpose of the Provider package in this app is to make the `GlobalBloc` available across all views. The underlying logic of the app lies in the corresponding BLoC of each functionality, and the Provider doesn't contribute in any of the logic code. The current version that I am using serves such purpose. 


Maybe I will consider pumping up the Provider package version in the following refactor, but I highly doubt it will make any difference in the app. It will only introduce breaking changes due to the change of the Provider syntax over last few months.


Thank you @MahdiPishguy for your feadback, I really appreciate your support!

**Comment by pishguy** [comment]
@KarimElghamry i get it, maybe you have right, but i think 3rd packages will be updated daily and after some month you should change  your opinion, i don't read source code  

i couldn't read source code , because i dont have free time now, i check that early and i'll try to update packages, then i'll send pull request you
